version: '3.9'
services:
  app:
    # for M1 processors
    platform: linux/arm64/v8
    container_name: app
    # ищет этот image, перед сборкой образа
    image: app
    build:
      # 🀄 контекст (папка из которой считается будет запущен Dockerfile)
      context: ..
      # 📂 указание на Dockerfile (сборка образа в случае его отсутствия)
      dockerfile: ./dockerfiles/Dockerfile
    environment:
      # допустимое имемна хоста в сети докера указано в Networks > Aliases (docker inspect postgres-service_db)
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@service_db:5432/db_name
    # CONFIG_NAME: config # ???
    volumes:
      # том для интерактивной работы над проектом (обновления в реальном времени)
      # docker compose restart <service> поднимает контейнер с обновлённой кодовой базой
      - ../app:/code/app
    ports:
      - 5000:5000
    # 🚀 команда при старте контейнера (переопределяет CMD в Dockerfile)
    command: "app"
    depends_on:
      - service_db

  service_db:  # имя хоста (имя контейнера в локльной сети)
    platform: linux/arm64/v8
    container_name: postgres-service_db # имя контейнера
    image: postgres:12 # образ, на основе которого собран
    environment: # переменные окружения, по сути являющиеся кредами для доступа к БД
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # расположение базы данных в контейнере
      # PGDATA: /var/lib/postgresql/data/pgdata
      PGDATA: /var/lib/postgresql/dat2/pgdata
    volumes:
    # том связывающий базу данных у хоста и контейнера
      # - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
      - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data2/pgdata
    ports:
      - "5432:5432" # соответствие портов на хост:контейнер